### PR TITLE
Fix lint-go

### PR DESCRIPTION
**Pull request by KevinFairise2**
What does this PR do?
---------------------

FIx lint-go

Which scenarios this will impact?
-------------------

Motivation
----------

Additional Notes
----------------

### CODE REVIEW

**Review by gjulianm — APPROVED** [review]
Sorry about that, did not notice the linter was failing. Thanks for fixing it!

**Comment by KevinFairise2** [comment]
> Sorry about that, did not notice the linter was failing. Thanks for fixing it!

No worries, actually you could not see it on the PR and the merge queue merged the PR with the linter failing. I update the configuration of the MQ so it should not happen again

**Pull request merged**
